[mysql]
    dbname     = "sample_db"
    host       = "mysql"
    port       = 3306
    user       = "root"
    pass       = "password"
    sslmode    = "false"
    whitelist = [
        "product",
        "category"
    ]